import '../../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../../../components/Header'
import Category from '../../../components/Category'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className="max-w-7xl mx-auto">
        <Header />
        <Category />
        {children}
      </body>
    </html>
  )
}
